name: Pull Request

on:
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    uses: ./.github/workflows/build-and-tests.yaml
    with:
      ref: ${{ github.event.pull_request.head.sha }}